### PR TITLE
Adding AppVeyor Support

### PR DESCRIPTION
**Pull request by Jeavon**
I have this building correctly on my fork so hopefully should be straight forward. (https://ci.appveyor.com/project/JeavonLeopold/umbraco-doc-type-grid-editor/)

Currently I have [commented the final NuGet package creation](https://github.com/Jeavon/umbraco-doc-type-grid-editor/blob/feature/appveyor-support/Build/package.proj#L189) due to the need for the package action to be executed to add the grid editor in the grid.editors.config.js file. I've tested it and it does create the NuGet packages correctly.

To get this working in NuGet you could look at [Shannon's new support](http://issues.umbraco.org/issue/U4-6402) for Grid editors in package.manifest (although I'm not sure it's working) otherwise a application startup event to execute the package actions, this might need a application key to know it's executed before....

Any questions/problems, let me know on Gitter or Skype.

### CODE REVIEW

**Comment by leekelleher** [comment]
As always, thanks @Jeavon! #h5yr

I'll read up about the [U4-6402](http://issues.umbraco.org/issue/U4-6402) feature - see if we can utilise it, as makes sense for the NuGet package.

**Comment by Jeavon** [comment]
Np :) I think U4-6402 makes complete sense, I just couldn't get it to work when I tried it out but Shannon is looking in to it. At least you can get AppVeyor building Umbraco CI packages for people to try out now!

**Comment by leekelleher** [comment]
I'm such a numpty, I forgot to set-up the AppVeyor project for this! :confounded:

Done! https://ci.appveyor.com/project/leekelleher/umbraco-doc-type-grid-editor

**Comment by Jeavon** [comment]
Cool! I think using the package manifest should work for a NuGet version as Shannon discovered the issue (U4-6402) was only where there were multiple gird editors defined (that might be fixed in Umbraco 7.2.5 anyhow)

**Pull request merged**
